[package]
name = "biosim_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biosim_core = { version = "0.1", path = "../biosim_core" }
clap = { version = "4.1", features = ["derive"] }
